apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: django-k8s:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              value: "dummy"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: DEBUG
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080